test_mode: False 
detect_thresh: 7
depth_img_count: 7
fps: 24  # ss01 Pub Rate
follow_distance: 0.1  # meters

topics:
    img_topic: "RGBHub"
    detections: "detections"
    resume_trigger: "resume_trigger"
    depth_req: "depth_req"
    bad_detections: "bad_detections"
    tf2: "tf2_poll"
    last_frame: "last_frame"
    avg_depth: "avg_depth"

frame_data:
    HEIGHT: 480
    WIDTH: 640

ss00_Liaison:
    depth_topic: "/camera/depth/image_raw"

ss02_Detector:
# Define the private parameters for ss02.
    yolo: {
        "yolo": "/home/hiwonder/yolov5",
        "weights": "/home/hiwonder/yolov5/weights/20231101_drone_weights.pt",
        "conf": 0.35
    }
    seek_thresh: 7.  # seconds
    debug: False

ss03_DataProcessor:
    debug: False
    density_thresh: 1.5
    max_accel: 5
    focal_length: 359.0439147949219
    principal_point:
    # [cx, cy]
        - 321.4884338378906
        - 181.9486541748047
