# Global planner
GlobalPlanner: # Also see: http://wiki.ros.org/global_planner
   old_navfn_behavior: false # If for some reason you want global_planner to fully reflect navfn's behavior, set it to true (and use default values for the other boolean parameters)
   use_quadratic: true # If true, use the quadratic approximation of the potential. Otherwise, use simpler calculations.
   use_dijkstra: false # If true, use dijkstra's algorithm. Otherwise, A* (set use_grid_path to true).
   use_grid_path: true # If true, create a path that follows the boundaries of the grid. Otherwise, use gradient descent.

   # Specify whether the planner is allowed to create plans that traverse unknown spaces. NOTE: If you use a hierarchical costmap_2d costmap with voxel or barrier layers,
   # You must also set the layer's track_unknown_space parameter to true, otherwise it will convert all unknown space to usable space
   allow_unknown: true

   planner_window_x: 0.0 # default 0.0
   planner_window_y: 0.0 # default 0.0
   default_tolerance: 0.0 # Tolerance of planner target point. The planner will try to create a plan that is as close as possible to the specified target but does not exceed default_tolerance

   visualize_potential: false # Specify whether to visualize the potential area calculated by PointCloud2.
